# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.2 on 2026-03-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_batch_batchstudent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBatchMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("avg_assignment_score", models.FloatField(default=0.0)),
                ("top_drop_off_node_id", models.IntegerField(blank=True, null=True)),
                ("students_at_risk_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="organizations.batch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("batch", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyOrgMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_active_users", models.IntegerField(default=0)),
                ("total_inactive_users", models.IntegerField(default=0)),
                ("avg_course_completion_rate", models.FloatField(default=0.0)),
                ("total_certificates_issued", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("organization", "date")},
            },
        ),
    ]
