# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0015_remove_batchstudent_unique_batch_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailybatchmetrics',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyorgmetrics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailybatchmetrics',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailybatchmetrics',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyorgmetrics',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyorgmetrics',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='dailybatchmetrics',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('batch', 'date'), name='unique_active_daily_batch_metrics'),
        ),
        migrations.AddConstraint(
            model_name='dailyorgmetrics',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'date'), name='unique_active_daily_org_metrics'),
        ),
    ]
