# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.2 on 2026-03-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_batch_batchstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Hex code e.g. #000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, help_text='Unique Organization Code', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_subdomain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_training_template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hq_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hq_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hq_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_active_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex code e.g. #FFFFFF', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, help_text='PNG/JPG URL <=2MB', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
