# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_accent_color_organization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='accent_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='default_training_template',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hq_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hq_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hq_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload PNG/JPG <=2MB', null=True, upload_to='organization_logos/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Hex code e.g. #FFFFFF', max_length=7),
        ),
    ]
