# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstudent',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
