# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_batchstudent_course_batchstudent_student_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstudent',
            name='course',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='batchstudent',
            name='student_id_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
