# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-16 06:59

import django.db.models.deletion
from django.db import migrations, models


def clear_empty_course_strings(apps, schema_editor):
    batch_student = apps.get_model('organizations', 'BatchStudent')
    batch_student.objects.filter(course="").update(course=None)

class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_course_thumbnail_image_url_course_thumbnail'),
        ('organizations', '0006_alter_batchstudent_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstudent',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(clear_empty_course_strings, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='batchstudent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_students', to='curriculum.course'),
        ),
    ]
