# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_course_thumbnail_image_url_course_thumbnail'),
        ('organizations', '0007_alter_batchstudent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='organizations.batch'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='curriculum.course'),
        ),
    ]
