# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_unique_batchstudent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchstudent',
            unique_together=set(),
        ),
    ]
