# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_alter_quizsubmission_status'),
        ('organizations', '0011_alter_batchstudent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='batches', to='curriculum.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_primary', to='curriculum.course'),
        ),
    ]
