# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-15 04:47

from django.db import migrations


def migrate_course_to_courses(apps, schema_editor):
    batch_class = apps.get_model('organizations', 'Batch')
    for batch in batch_class.objects.exclude(course__isnull=True):
        batch.courses.add(batch.course)

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_batch_courses_alter_batch_course'),
    ]

    operations = [
        migrations.RunPython(migrate_course_to_courses),
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
    ]
