# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_remove_batchstudent_unique_batch_student_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_active_org_code',
        ),
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_active_org_subdomain',
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Unique Organization Code', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='custom_subdomain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code', ''), _negated=True), models.Q(('code__isnull', True), _negated=True)), fields=('code',), name='unique_active_org_code'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('custom_subdomain', ''), _negated=True), models.Q(('custom_subdomain__isnull', True), _negated=True)), fields=('custom_subdomain',), name='unique_active_org_subdomain'),
        ),
    ]
