# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-06-11 06:59

import lms_core.utils_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_remove_organization_unique_active_org_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload PNG/JPG <=2MB', max_length=500, null=True, upload_to=lms_core.utils_storage.organization_directory_path),
        ),
    ]
