# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-06-15 11:57

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_batches(apps, schema_editor):
    org_member_model = apps.get_model('organizations', 'OrganizationMember')
    for member in org_member_model.objects.filter(batch__isnull=False):
        member.batches.add(member.batch)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='organizations.batch'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members_legacy', to='organizations.batch'),
        ),
        migrations.RunPython(copy_legacy_batches, reverse_code=migrations.RunPython.noop),
    ]
