# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-06-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organizationmember_batches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='batch',
        ),
    ]
