# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_remove_organizationmember_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='uuid',
            field=models.UUIDField(blank=True, help_text='Unique Membership UUID', null=True),
        ),
    ]
