# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-16 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_seed_membership_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Membership UUID', unique=True),
        ),
    ]
