# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-16 10:23

import django.db.models.deletion
from django.db import migrations, models


def update_student_ids(apps, schema_editor):
    batch_student_model = apps.get_model('organizations', 'BatchStudent')
    org_member_model = apps.get_model('organizations', 'OrganizationMember')
    
    for bs in batch_student_model.objects.select_related('batch').all():
        om = org_member_model.objects.filter(
            user_id=bs.student_id, 
            organization_id=bs.batch.organization_id
        ).first()
        if om:
            bs.student_id = om.uuid
            bs.save(update_fields=['student_id'])
        else:
            bs.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_alter_organizationmember_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='organizations.organizationmember', to_field='uuid', db_constraint=False),
        ),
        migrations.RunPython(update_student_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='batchstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='organizations.organizationmember', to_field='uuid'),
        ),
    ]
