# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-16 17:44

from django.db import migrations, models


def populate_roles_from_role(apps, schema_editor):
    org_member_model = apps.get_model('organizations', 'OrganizationMember')
    for member in org_member_model.objects.all():
        if member.role_id:
            member.roles.add(member.role_id)

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_alter_batchstudent_student'),
        ('rbac', '0006_alter_userrole_unique_together_role_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='organization_members', to='rbac.role'),
        ),
        migrations.RunPython(populate_roles_from_role, reverse_code=migrations.RunPython.noop),
    ]
