# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-09-09 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_organizationmember_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_org_level',
            field=models.BooleanField(default=False, help_text='Designates whether this batch is an organization-level batch.'),
        ),
        migrations.AddField(
            model_name='batch',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text='Reporting manager for org-level batch (FK to User UUID).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
