# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-09-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_batch_is_org_level_batch_reporting_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_org_level',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='reporting_manager',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='primary_color',
        ),
    ]
