# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

"""
Django settings for lms_core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Reading .env file
environ.Env.read_env(BASE_DIR / ".env")

# ── AWS SECRETS MANAGER INTEGRATION ──────────────────────────────────────────
aws_secrets = {}
if env.bool("USE_AWS_SECRETS", default=False):
    try:
        import boto3
        from botocore.exceptions import ClientError
    except ImportError:
        raise ImportError(
            "The 'boto3' library is required to use AWS Secrets Manager. "
            "Please run 'pip install boto3' or 'poetry add boto3'."
        )

    secret_name = env.str("AWS_SECRETS_NAME")
    region_name = env.str("AWS_REGION_NAME", default="ap-south-1")

    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )

    try:
        get_secret_value_response = client.get_secret_value(SecretId=secret_name)
        if "SecretString" in get_secret_value_response:
            import json
            aws_secrets = json.loads(get_secret_value_response["SecretString"])
    except Exception as e:
        raise ConnectionError(f"Error fetching secrets from AWS Secrets Manager '{secret_name}': {e}")


def get_secret(key, default=environ.Env.NOTSET, cast=None):
    """
    Retrieves a secret from AWS Secrets Manager if available; otherwise falls back to environment/defaults.
    """
    val = aws_secrets.get(key)

    if val is None:
        kwargs = {}
        if default is not environ.Env.NOTSET:
            kwargs["default"] = default
        
        if cast == bool:
            return env.bool(key, **kwargs)
        elif cast == int:
            return env.int(key, **kwargs)
        elif cast == list:
            return env.list(key, **kwargs)
        else:
            return env.str(key, **kwargs)

    # Cast the value appropriately
    if cast == bool:
        if isinstance(val, bool):
            return val
        return str(val).lower() in ("true", "1", "yes")
    elif cast == int:
        return int(val)
    elif cast == list:
        if isinstance(val, list):
            return val
        return [x.strip() for x in str(val).split(",") if x.strip()]
    return str(val)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret("SECRET_KEY", default="django-insecure-local-dev-key-12345")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_secret("DEBUG", cast=bool)

ALLOWED_HOSTS = get_secret("ALLOWED_HOSTS", default=["*"], cast=list)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
FRONTEND_URL = get_secret("FRONTEND_URL", default="http://localhost:5173")
CSRF_TRUSTED_ORIGINS = list(
    dict.fromkeys(
        get_secret("CSRF_TRUSTED_ORIGINS", default=[FRONTEND_URL], cast=list)
        + ["http://localhost:5173", "http://localhost:5174"]
    )
)
BACKEND_PUBLIC_URL = get_secret("BACKEND_PUBLIC_URL", default="")


# ── EMAIL SETTINGS ────────────────────────────────────────────────────────────
EMAIL_BACKEND = get_secret("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = get_secret("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = get_secret("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = get_secret("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = get_secret("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = get_secret("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = get_secret("DEFAULT_FROM_EMAIL", default="noreply@lms.com")

# ── CORS ──────────────────────────────────────────────────────────────────────



CORS_ALLOW_ALL_ORIGINS = get_secret("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)
CORS_ALLOWED_ORIGINS = list(
    dict.fromkeys(
        get_secret(
            "CORS_ALLOWED_ORIGINS",
            default=[],
            cast=list,
        )
        + [
            FRONTEND_URL.rstrip("/"),
            "http://localhost:5173",
            "http://localhost:5174",
        ]
    )
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_PRIVATE_NETWORK = True

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "accounts",
    "rbac",
    "organizations",
    "curriculum",
    "gamification",
    "analytics",
    "storages",
    "django_celery_results",
]

AUTH_USER_MODEL = "accounts.User"
SILENCED_SYSTEM_CHECKS = ["auth.E003"]

# ── DRF ──────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Rates for the unauthenticated auth endpoints (see accounts/views.py).
    # Clients are identified by IP; set NUM_PROXIES when running behind a proxy.
    "DEFAULT_THROTTLE_RATES": {
        "auth_login": get_secret("THROTTLE_RATE_LOGIN", default="5/minute"),
        "auth_password_reset_email": get_secret("THROTTLE_RATE_PASSWORD_RESET_EMAIL", default="5/hour"),
        "auth_token": get_secret("THROTTLE_RATE_AUTH_TOKEN", default="10/minute"),
    },
    "NUM_PROXIES": get_secret("NUM_PROXIES", default=None, cast=int),
}

# ── Simple JWT ────────────────────────────────────────────────────────────────
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ── drf-spectacular (OpenAPI) ─────────────────────────────────────────────────
SPECTACULAR_SETTINGS = {
    "TITLE": "LMS API",
    "DESCRIPTION": (
        "Learning Management System — REST API.\n\n"
        "**Authentication:** All protected endpoints require a Bearer JWT token.\n"
        "Use `POST /api/auth/login/` with your email and password to obtain tokens, then click **Authorize** above."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENT_SECURITY_SCHEMES": {
        "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayRequestDuration": True,
        "filter": True,
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lms_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lms_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

vault_db_url = get_secret("DATABASE_URL", default=None)
if vault_db_url:
    DATABASES = {
        "default": env.db_url_config(vault_db_url)
    }
else:
    db_user = get_secret("DB_USER", default="postgres")
    db_password = get_secret("DB_PASSWORD", default="postgres")
    db_host = get_secret("DB_HOST")
    db_port = get_secret("DB_PORT", default="5432")
    db_name = get_secret("DB_NAME", default="lms-llm")
    default_db_url = f"postgres://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
    DATABASES = {
        "default": env.db_url(
            "DATABASE_URL",
            default=default_db_url
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ── STORAGE (AWS S3 vs LOCAL) ──────────────────────────────────────────────────
USE_S3 = get_secret("USE_S3", default=False, cast=bool)

if USE_S3:
    AWS_ACCESS_KEY_ID = get_secret("AWS_S3_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = get_secret("AWS_S3_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = get_secret("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = get_secret("AWS_S3_REGION_NAME", default="ap-south-1")
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # MEDIA_URL is not strictly needed for S3 as Django-Storages generates absolute URLs
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# ── CACHING & REDIS ────────────────────────────────────────────────────────────
DJANGO_REDIS_IGNORE_EXCEPTIONS = True

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": get_secret("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        }
    }
}

# ── CELERY ────────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = get_secret("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = get_secret("CELERY_RESULT_BACKEND", default="django-db")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# CELERY SETTING
CELERY_TASK_ALWAYS_EAGER = get_secret("CELERY_TASK_ALWAYS_EAGER", default=False, cast=bool)

