# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-05-06 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_alter_user_options_user_deleted_at_user_is_deleted_and_more",
        ),
        ("organizations", "0016_remove_organization_unique_active_org_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_invited_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent invite/reinvite.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reinvite_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times a reinvite has been sent."
            ),
        ),
        migrations.CreateModel(
            name="InviteToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this token expires (created_at + 7 days)."
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, help_text="1 = original invite; 2+ = re-invite."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite_tokens",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
