# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.2 on 2026-02-23 21:14

from django.db import migrations


def create_default_roles(apps, schema_editor):
    role = apps.get_model("rbac", "Role")
    roles = [
        {"name": "superadmin", "description": "Full system access"},
        {"name": "teacher", "description": "Course creator and instructor"},
        {"name": "student", "description": "Learner enrolled in courses"},
    ]
    for role_data in roles:
        role.objects.get_or_create(
            name=role_data["name"], defaults={"description": role_data["description"]}
        )


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0002_alter_role_name"),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
