# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.2 on 2026-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0003_seed_initial_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super-Admin"),
                    ("org_admin", "Org Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
