# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.2 on 2026-02-24 20:21

from django.db import migrations


def create_org_admin(apps, schema_editor):
    role = apps.get_model("rbac", "Role")
    role.objects.get_or_create(
        name="org_admin", defaults={"description": "Organization Admin"}
    )


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0004_alter_role_name"),
    ]

    operations = [
        migrations.RunPython(create_org_admin),
    ]
