# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.2 on 2026-03-01 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

CURRICULUM_NODE = "curriculum.node"

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_batch_batchstudent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice Question"),
                            ("Coding", "Coding Assignment"),
                            ("Short Answer", "Short Answer"),
                            ("FileUpload", "File Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="Instructions or the question prompt."),
                ),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                ("passing_score_percentage", models.PositiveIntegerField(default=0)),
                (
                    "expected_answer_schema",
                    models.JSONField(
                        blank=True,
                        help_text="Configurable schema for auto-grading.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Graded", "Graded"),
                            ("Needs Manual Review", "Needs Manual Review"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(help_text="Student's answers.")),
                ("awarded_score", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="curriculum.assessment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("thumbnail_image_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Archived", "Archived"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sequence_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sequence_order", models.PositiveIntegerField(default=0)),
                (
                    "drip_delay_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of days to wait after batch start before unlocking.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="curriculum.module",
                    ),
                ),
                (
                    "prerequisite_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_nodes",
                        to=CURRICULUM_NODE,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("PDF", "PDF"),
                            ("Article", "Article"),
                            ("SCORM", "SCORM"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for external content like videos or files stored in S3.",
                        null=True,
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, help_text="Markdown or rich text for articles."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_material",
                        to=CURRICULUM_NODE,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="node",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment",
                to=CURRICULUM_NODE,
            ),
        ),
        migrations.CreateModel(
            name="StudentNodeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Locked", "Locked"),
                            ("Unlocked", "Unlocked"),
                            ("In_Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Locked",
                        max_length=20,
                    ),
                ),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to=CURRICULUM_NODE,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "node")},
            },
        ),
    ]
