# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_course_thumbnail_image_url_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload PDF, Doc, or Video files.', null=True, upload_to='learning_materials/'),
        ),
        migrations.AddField(
            model_name='node',
            name='focus_areas',
            field=models.TextField(blank=True, help_text='What should learners focus on?'),
        ),
        migrations.AddField(
            model_name='node',
            name='quick_outline',
            field=models.TextField(blank=True, help_text='Brief outline of the node content.'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='content_type',
            field=models.CharField(choices=[('Link', 'Link'), ('PDF', 'PDF'), ('Doc', 'Doc'), ('Video', 'Video')], max_length=20),
        ),
    ]
