# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_learningmaterial_content_file_node_focus_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
