# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_quiz_quizquestion_quizoption_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='curriculum.node'),
        ),
    ]
