# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_quiz_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='timer_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Quiz timer in minutes. Null means no timer.', null=True),
        ),
    ]
