# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_quizsubmission_quizanswer_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='awarded_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
