# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_coursecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submissions/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='payload',
            field=models.JSONField(blank=True, help_text="Student's task content (links, text, etc.)", null=True),
        ),
    ]
