# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_task_attachment_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='allow_multiple_correct',
            field=models.BooleanField(default=False),
        ),
    ]
