# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_quizquestion_allow_multiple_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Minimum score percentage to pass'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
