# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_quiz_pass_percentage_quizsubmission_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='raw_answers_data',
            field=models.JSONField(blank=True, db_column='answers', null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='status',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
