# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_quizsubmission_attempt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='status',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], default='Failed', max_length=20),
        ),
    ]
