# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_alter_quizsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Graded', 'Graded'), ('Needs Manual Review', 'Needs Manual Review')], default='Pending', max_length=30),
        ),
    ]
