# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-06-11 06:59

import lms_core.utils_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_alter_coursecertificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=lms_core.utils_storage.organization_directory_path),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload PDF, Doc, or Video files.', max_length=500, null=True, upload_to=lms_core.utils_storage.organization_directory_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=lms_core.utils_storage.organization_directory_path),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submission_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=lms_core.utils_storage.organization_directory_path),
        ),
    ]
