# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.5 on 2026-06-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_codingquestion_codingsubmission_codingtestcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes for the student to solve the question', null=True),
        ),
    ]
