# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.5 on 2026-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_codingquestion_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='allowed_languages',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed language keys (e.g. ['python', 'java']). If non-empty, student can choose from this list. If empty, falls back to programming_language."),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_practice',
            field=models.BooleanField(default=False, help_text='If true, student may choose any supported language for this coding node.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='programming_language',
            field=models.CharField(blank=True, default='', help_text="Required language for Coding type (e.g. 'python'). Teacher sets this.", max_length=50),
        ),
    ]
