# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_assessment_allowed_languages_assessment_is_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='must_pass_to_continue',
            field=models.BooleanField(default=False, help_text="If True, the student cannot continue to the next node until an attempt scores at least pass_percentage (hard gate — 'Retake'). If False, the result is recorded but progress is never blocked ('Continue')."),
        ),
    ]
