# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_quiz_must_pass_to_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='on_fail_behavior',
            field=models.CharField(choices=[('retake', 'Retake — student must retake until passing'), ('continue', 'Continue — student can continue regardless')], default='continue', help_text="'retake' blocks the student until they pass (hard gate). 'continue' records the result but never blocks progress.", max_length=20),
        ),
    ]
