# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3

from django.db import migrations

def _reorder_single_module(module, node_model):
    nodes = list(node_model.objects.filter(module_id=module.id, is_deleted=False).order_by('sequence_order', '-updated_at', 'id'))
    if not nodes:
        return

    for i, node in enumerate(nodes, start=1):
        prev_node = nodes[i - 2] if i > 1 else None
        prev_node_id = prev_node.id if prev_node else None

        changed = False
        if node.sequence_order != i:
            node.sequence_order = i
            changed = True
        if node.prerequisite_node_id != prev_node_id:
            node.prerequisite_node_id = prev_node_id
            changed = True

        if changed:
            node.save(update_fields=['sequence_order', 'prerequisite_node'])

def reorder_all_existing_nodes(apps, schema_editor):
    module_model = apps.get_model('curriculum', 'Module')
    node_model = apps.get_model('curriculum', 'Node')

    for module in module_model.objects.all():
        _reorder_single_module(module, node_model)

class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_add_on_fail_behavior_to_quiz'),
    ]

    operations = [
        migrations.RunPython(reorder_all_existing_nodes, reverse_code=migrations.RunPython.noop),
    ]
