# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_add_on_fail_behavior_to_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
