# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_codingquestion_s3_key'),
        ('curriculum', '0029_reorder_existing_nodes'),
    ]

    operations = [
    ]
