# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_merge_20260714_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, default=''),
        ),
    ]
