# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-07-16 10:23

import django.db.models.deletion
from django.db import migrations, models

ORGANIZATION_MEMBER = 'organizations.organizationmember'

def migrate_course_teachers(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        # Get all old assignments
        cursor.execute("SELECT course_id, user_id FROM curriculum_course_teachers_old")
        old_assignments = cursor.fetchall()
        
        # Get mappings of (user_id, organization_id) to OrganizationMember.id (active first)
        cursor.execute("SELECT id, user_id, organization_id, is_deleted FROM organizations_organizationmember ORDER BY is_deleted ASC")
        members = cursor.fetchall()
        
        # Build lookup dict
        member_lookup = {}
        for m_id, u_id, org_id, is_deleted in members:
            member_lookup[(str(u_id), org_id)] = m_id
            
        # Get course organizations
        cursor.execute("SELECT id, organization_id FROM curriculum_course")
        courses = cursor.fetchall()
        course_org_lookup = dict(courses)
        
        # Insert new assignments
        new_records = []
        for course_id, user_id in old_assignments:
            org_id = course_org_lookup.get(course_id)
            if org_id:
                member_id = member_lookup.get((str(user_id), org_id))
                if member_id:
                    new_records.append((course_id, member_id))
                    
        # Batch insert to prevent performance issue
        if new_records:
            cursor.executemany(
                "INSERT INTO curriculum_course_teachers (course_id, organizationmember_id) VALUES (%s, %s)",
                new_records
            )

class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_alter_codingquestion_s3_key'),
        ('organizations', '0023_alter_batchstudent_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=ORGANIZATION_MEMBER, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='codingsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_code_submissions', to=ORGANIZATION_MEMBER, to_field='uuid'),
        ),
        
        # Custom ManyToMany Transition using SeparateDatabaseAndState to prevent psycopg UUID casting crash
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("ALTER TABLE curriculum_course_teachers RENAME TO curriculum_course_teachers_old;"),
                migrations.RunSQL("""
                    CREATE TABLE curriculum_course_teachers (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        course_id bigint NOT NULL REFERENCES curriculum_course(id) ON DELETE CASCADE,
                        organizationmember_id bigint NOT NULL REFERENCES organizations_organizationmember(id) ON DELETE CASCADE,
                        CONSTRAINT unique_course_teacher UNIQUE (course_id, organizationmember_id)
                    );
                    CREATE INDEX curriculum_course_teachers_course_id ON curriculum_course_teachers(course_id);
                    CREATE INDEX curriculum_course_teachers_organizationmember_id ON curriculum_course_teachers(organizationmember_id);
                """),
                migrations.RunPython(migrate_course_teachers, reverse_code=migrations.RunPython.noop),
                migrations.RunSQL("DROP TABLE curriculum_course_teachers_old;"),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='course',
                    name='teachers',
                    field=models.ManyToManyField(blank=True, related_name='assigned_courses', to=ORGANIZATION_MEMBER),
                ),
            ]
        ),
        
        migrations.AlterField(
            model_name='coursecertificate',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_course_certificates', to=ORGANIZATION_MEMBER, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='coursecertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to=ORGANIZATION_MEMBER, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=ORGANIZATION_MEMBER, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='studentnodeprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to=ORGANIZATION_MEMBER, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=ORGANIZATION_MEMBER, to_field='uuid'),
        ),
    ]
