# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-09-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0033_alter_coursecertificate_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='node',
        ),
        migrations.RemoveField(
            model_name='codingtestcase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='codingsubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='codingsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='codingtestcaseresult',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='codingtestcaseresult',
            name='test_case',
        ),
        migrations.RemoveConstraint(
            model_name='coursecertificate',
            name='unique_active_course_cert_id',
        ),
        migrations.RemoveConstraint(
            model_name='coursecertificate',
            name='unique_active_student_course_cert',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='content_file',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='node',
            name='drip_delay_days',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='must_pass_to_continue',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='on_fail_behavior',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pass_percentage',
        ),
        migrations.DeleteModel(
            name='CodingQuestion',
        ),
        migrations.DeleteModel(
            name='CodingSubmission',
        ),
        migrations.DeleteModel(
            name='CodingTestCase',
        ),
        migrations.DeleteModel(
            name='CodingTestCaseResult',
        ),
        migrations.DeleteModel(
            name='CourseCertificate',
        ),
    ]
