# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.1.1 on 2026-10-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0034_remove_codingquestion_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='allowed_languages',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='is_practice',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='programming_language',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assignment_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('Short Answer', 'Short Answer'), ('FileUpload', 'File Upload')], max_length=20),
        ),
    ]
