# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.1.2 on 2026-10-08 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0037_convert_heading_nodes_to_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=70, help_text='Minimum score (0-100) a student needs to pass the quiz.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
