# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.3 on 2026-09-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_certificate_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='organization',
        ),
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_active_gamification_cert_student_course',
        ),
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_active_gamification_cert_code',
        ),
        migrations.RemoveConstraint(
            model_name='userbadge',
            name='unique_active_user_badge',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
