# SPDX-FileCopyrightText: 2026 Pace Wisdom Solutions Pvt. Ltd.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.1.2 on 2026-10-08 08:27

import django.db.models.deletion
from django.db import migrations, models


def backfill_rewards_for_completed_nodes(apps, schema_editor):
    """
    Record existing completions as already rewarded so that re-saving a
    completed progress row after this migration does not award points again.
    """
    StudentNodeProgress = apps.get_model('curriculum', 'StudentNodeProgress')
    NodeCompletionReward = apps.get_model('gamification', 'NodeCompletionReward')

    completed = (
        StudentNodeProgress.objects
        .filter(status='Completed', is_deleted=False)
        .values_list('student_id', 'node_id')
        .distinct()
    )
    # student_id holds the OrganizationMember uuid (to_field='uuid')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    member_ids = dict(OrganizationMember.objects.values_list('uuid', 'id'))

    rewards = [
        NodeCompletionReward(organization_member_id=member_ids[student_uuid], node_id=node_id, points=10)
        for student_uuid, node_id in completed.iterator()
        if student_uuid in member_ids
    ]
    NodeCompletionReward.objects.bulk_create(rewards, batch_size=1000, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0035_remove_assessment_coding_fields'),
        ('gamification', '0004_remove_badge_organization_and_more'),
        ('organizations', '0026_remove_batch_is_org_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeCompletionReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_rewards', to='curriculum.node')),
                ('organization_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_completion_rewards', to='organizations.organizationmember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization_member', 'node'), name='unique_node_completion_reward')],
            },
        ),
        migrations.RunPython(backfill_rewards_for_completed_nodes, migrations.RunPython.noop),
    ]
