# Generated by Django 6.0.3 on 2026-10-08 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0035_remove_assessment_coding_fields'),
        ('gamification', '0004_remove_badge_organization_and_more'),
        ('organizations', '0026_remove_batch_is_org_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Standard Completion Template', max_length=255)),
                ('title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('subtitle', models.CharField(default='This is proudly presented to', max_length=255)),
                ('completion_text', models.TextField(default='for successfully completing the prescribed course and fulfilling all curriculum and assessment requirements.')),
                ('signatory_title', models.CharField(default='Authorized Signatory', max_length=255)),
                ('signatory_name', models.CharField(default='Director of Academics', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_id', models.CharField(db_index=True, help_text='Verification code, e.g. CERT-C-1-A8F7F314', max_length=100, unique=True)),
                ('certificate_type', models.CharField(choices=[('Course', 'Course'), ('Assessment', 'Assessment')], default='Course', max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='curriculum.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='gamification.certificatetemplate')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'course'), name='unique_active_gamification_cert_student_course'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('certificate_id',), name='unique_active_gamification_cert_code')],
            },
        ),
    ]
