# Generated by Django 6.0.3 on 2026-10-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_certificatetemplate_certificate'),
        ('gamification', '0005_node_completion_reward'),
    ]

    operations = [
    ]
